[package]
name = "{{ project_name }}"
version = "0.1.0"
edition = "2021"

[dependencies.ohkami]
git = "https://github.com/ohkami-rs/ohkami"
branch = "v0.22"
features = ["rt_lambda"]

[dependencies]
lambda_runtime = "0.13"
tokio = { version = "1", features = ["macros"] }
