name = "worker_yew_spa"
main = "build/worker/shim.mjs"
compatibility_date = "2024-04-19"

# `worker-build` is required (run `cargo install worker-build` to install)

# `trunk` CLI is required

[build]
command = "test $OHKAMI_WORKER_DEV && worker-build --dev || worker-build"
# in dev, run `trunk serve --watch src/ui --open` in another terminal window
