name = "ohkami-worker"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-09"

# `worker-build` is required (run `cargo install worker-build` to install)

[build]
command = "test $OHKAMI_WORKER_DEV && worker-build --dev || worker-build"
